
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "leftADD_OPleftMUL_OPrightUMINUSBOOL INT NUMBER ADD_OP MUL_OP INCREMENT_OP IDENTIFIER TYPE ON_SE_LE_REFAIT_UNE_PETITE_FOIS PAS_MAL TROEUW JE_VAIS_BOSSER_CETTE_SEMAINE SERIEUX JE_PASSE_MON_ANNEE COCHON_EGAL_PORC FERMEZ_VOS_ORDINATEUR ONE_POINT PAS_TERRIBLE TRUE FALSE programme : statement  programme : statement ';' programme  statement : assignation\n        | declaration\n        | structure  statement : PAS_MAL expression  structure : ON_SE_LE_REFAIT_UNE_PETITE_FOIS expression '{' programme '}' expression : expression ADD_OP expression\n            | expression MUL_OP expressionexpression : NUMBER\n        | INT\n        | boolean\n        | IDENTIFIER  boolean : TRUE\n                | FALSEexpression : '(' expression ')'  expression : ADD_OP expression %prec UMINUS expression : IDENTIFIER INCREMENT_OP  declaration : TYPE IDENTIFIER  assignation : IDENTIFIER '=' expression "
    
_lr_action_items = {'PAS_MAL':([0,10,30,],[6,6,6,]),'IDENTIFIER':([0,6,8,9,10,12,17,20,24,25,30,],[7,16,21,16,7,16,16,16,16,16,7,]),'TYPE':([0,10,30,],[8,8,8,]),'ON_SE_LE_REFAIT_UNE_PETITE_FOIS':([0,10,30,],[9,9,9,]),'$end':([1,2,3,4,5,11,13,14,15,16,18,19,21,23,26,27,29,31,32,33,35,],[0,-1,-3,-4,-5,-6,-10,-11,-12,-13,-14,-15,-19,-2,-17,-18,-20,-8,-9,-16,-7,]),'}':([2,3,4,5,11,13,14,15,16,18,19,21,23,26,27,29,31,32,33,34,35,],[-1,-3,-4,-5,-6,-10,-11,-12,-13,-14,-15,-19,-2,-17,-18,-20,-8,-9,-16,35,-7,]),';':([2,3,4,5,11,13,14,15,16,18,19,21,26,27,29,31,32,33,35,],[10,-3,-4,-5,-6,-10,-11,-12,-13,-14,-15,-19,-17,-18,-20,-8,-9,-16,-7,]),'NUMBER':([6,9,12,17,20,24,25,],[13,13,13,13,13,13,13,]),'INT':([6,9,12,17,20,24,25,],[14,14,14,14,14,14,14,]),'(':([6,9,12,17,20,24,25,],[17,17,17,17,17,17,17,]),'ADD_OP':([6,9,11,12,13,14,15,16,17,18,19,20,22,24,25,26,27,28,29,31,32,33,],[12,12,24,12,-10,-11,-12,-13,12,-14,-15,12,24,12,12,-17,-18,24,24,-8,-9,-16,]),'TRUE':([6,9,12,17,20,24,25,],[18,18,18,18,18,18,18,]),'FALSE':([6,9,12,17,20,24,25,],[19,19,19,19,19,19,19,]),'=':([7,],[20,]),'MUL_OP':([11,13,14,15,16,18,19,22,26,27,28,29,31,32,33,],[25,-10,-11,-12,-13,-14,-15,25,-17,-18,25,25,25,-9,-16,]),'{':([13,14,15,16,18,19,22,26,27,31,32,33,],[-10,-11,-12,-13,-14,-15,30,-17,-18,-8,-9,-16,]),')':([13,14,15,16,18,19,26,27,28,31,32,33,],[-10,-11,-12,-13,-14,-15,-17,-18,33,-8,-9,-16,]),'INCREMENT_OP':([16,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programme':([0,10,30,],[1,23,34,]),'statement':([0,10,30,],[2,2,2,]),'assignation':([0,10,30,],[3,3,3,]),'declaration':([0,10,30,],[4,4,4,]),'structure':([0,10,30,],[5,5,5,]),'expression':([6,9,12,17,20,24,25,],[11,22,26,28,29,31,32,]),'boolean':([6,9,12,17,20,24,25,],[15,15,15,15,15,15,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programme","S'",1,None,None,None),
  ('programme -> statement','programme',1,'p_programme_statement','parser5.py',9),
  ('programme -> statement ; programme','programme',3,'p_programme_recursive','parser5.py',13),
  ('statement -> assignation','statement',1,'p_statement','parser5.py',17),
  ('statement -> declaration','statement',1,'p_statement','parser5.py',18),
  ('statement -> structure','statement',1,'p_statement','parser5.py',19),
  ('statement -> PAS_MAL expression','statement',2,'p_statement_print','parser5.py',23),
  ('structure -> ON_SE_LE_REFAIT_UNE_PETITE_FOIS expression { programme }','structure',5,'p_structure','parser5.py',27),
  ('expression -> expression ADD_OP expression','expression',3,'p_expression_op','parser5.py',31),
  ('expression -> expression MUL_OP expression','expression',3,'p_expression_op','parser5.py',32),
  ('expression -> NUMBER','expression',1,'p_expression_num_or_var','parser5.py',36),
  ('expression -> INT','expression',1,'p_expression_num_or_var','parser5.py',37),
  ('expression -> boolean','expression',1,'p_expression_num_or_var','parser5.py',38),
  ('expression -> IDENTIFIER','expression',1,'p_expression_num_or_var','parser5.py',39),
  ('boolean -> TRUE','boolean',1,'p_boolean','parser5.py',43),
  ('boolean -> FALSE','boolean',1,'p_boolean','parser5.py',44),
  ('expression -> ( expression )','expression',3,'p_expression_paren','parser5.py',48),
  ('expression -> ADD_OP expression','expression',2,'p_minus','parser5.py',52),
  ('expression -> IDENTIFIER INCREMENT_OP','expression',2,'p_increment','parser5.py',56),
  ('declaration -> TYPE IDENTIFIER','declaration',2,'p_declaration','parser5.py',60),
  ('assignation -> IDENTIFIER = expression','assignation',3,'p_assign','parser5.py',64),
]
